import { Task } from "@/model/Task";

export const initialTasks: Task[] = [
  {
    id: 1,
    title: "Task 1",
    description: "Initialize the taskboard",
    persona: "Employee",
    group: 1,
    status: "active",
  },
  {
    id: 2,
    title: "Task 2",
    description: "fix dashboard",
    persona: "Employee",
    group: 1,
    status: "pending",
  },
  {
    id: 3,
    title: "Task 3",
    description: "Monitor activity",
    persona: "Employee",
    group: 1,
    status: "pending",
  },
  {
    id: 4,
    title: "Task 4",
    description: "analyze json",
    persona: "Employee",
    group: 1,
    status: "pending",
  },
  {
    id: 5,
    title: "Task 5",
    description: "maintainance",
    persona: "Employee",
    group: 1,
    status: "pending",
  },
  {
    id: 6,
    title: "Task 6",
    description: "cache storage",
    persona: "Employee",
    group: 1,
    status: "pending",
  },
  {
    id: 7,
    title: "Task 7",
    description: "check db",
    persona: "Employee",
    group: 1,
    status: "pending",
  },
  {
    id: 8,
    title: "Task 8",
    description: "fix branches",
    persona: "Employee",
    group: 1,
    status: "pending",
  },
  {
    id: 9,
    title: "Task 9",
    description: "fix pipeline",
    persona: "Employee",
    group: 1,
    status: "pending",
  },
  {
    id: 10,
    title: "Task 10",
    description: "generate report",
    persona: "Employee",
    group: 1,
    status: "pending",
  },
];
